version: '3'
services:
  nginx:
    image: "nginx:latest"
    container_name: "nginx_container"
    restart: always
    ports:
      - "7777:80"
  flask-app:
    image: "ritthyk/flask-app:latest"
    container_name: "ritthyk_container"
    restart: always
    ports:
      - "8800:5000"  
      